### ISSUE TITLE
StackOverflowError while calculating quantiles via JuliaDB

### ISSUE THREAD

**Issue by MaximilianJHuber** [joshday/OnlineStats.jl#113] opened 2018-03-22 18:46 UTC
A groupreduce on a table with about 3 million entries in 5 chunks (it is a subset of  a table with 2 billion entries in 812 chunks) takes forever and leads to a `StackOverflowError `. The grouping variable is a binary or missing, the value is an `Int`.

Or is this issue fixed on master? [I cannot check](https://github.com/joshday/OnlineStats.jl/issues/112).

```
groupreduce(Quantile([.25, .5, .75], OMAS()), table, :binary, select=:value)
```

**Comment by joshday** [comment] 2018-03-22 21:42
Can you paste your error message? Or put in a gist if it's long?

**Comment by MaximilianJHuber** [comment] 2018-03-22 21:59
I am afraid not. It just gives some `WARNING: _fit!(o::OnlineStat, y, w) is deprecated, use fit!(o::OnlineStat, y, w) instead.`, then works for a bit, then writes
```
On worker 4:
StackOverflowError:
```
no details on the error message...

When I `collect` the distributed table before, it works fine, but then again, that's not exactly the purpose of OnlineStats.

**Comment by joshday** [comment] 2018-04-20 20:53
@MaximilianJHuber can this be closed?  There's been a round of OnlineStats/IndexedTables/JuliaDB since this was opened.

**Comment by joshday** [comment] 2018-04-21 16:49
Okay, thanks for the update!  I'll ping @shashi in case he has any ideas.  It's strange that `Mean` works and `Quantile` fails, but it looks like the issue is in JuliaDB.

**Comment by MaximilianJHuber** [comment] 2018-04-21 16:53
Mhm, I think so too. Thanks, for the continuing support!

**Comment by JeffBezanson** [comment] 2018-11-08 21:12
Worth trying this now that a 1.0-compatible version of JuliaDB is available. I'm not sure it's fixed but will be interesting to see what happens.

**Comment by joshday** [comment] 2019-09-05 08:56
I think this issue is with JuliaDB, so I'll close this for now.

**Closed by joshday** 2019-09-05 08:56 UTC
