### ISSUE TITLE
Moving window online stats

### ISSUE THREAD

**Issue by iceblue25** [joshday/OnlineStats.jl#37] opened 2015-08-26 00:12 UTC
It would be nice if these online statistics can return the statistic over the last X samples rather than the start. For example , moving average.

**Comment by tbreloff** [comment] 2015-08-26 00:47
Thanks for the interest.  This is a duplicate of #20, so I'm going to close it.  As I said there, moving windows aren't exactly "online statistics" in the sense that you need a history of data to compute, but I do agree they are important to support.  We have the pieces, just need to put them together nicely.

**Closed by tbreloff** 2015-08-26 00:47 UTC

**Comment by iceblue25** [comment] 2015-08-28 05:24
Thanks for the reply but I am not sure if that is true. 

You can compute online moving window in 2 ways.

One is to wait for the circular buffer to fill and then start computing the stats.

The second is to start right away based on the window size and increase it to its maximum size.

For example, the when 1 sample appears the window size is 1. When two samples appear the window size is 2. 
For example [1] appears mean is 1
then [2] appears and circular buffer has [1 2] and mean is 1.5

The two approaches converge to the same value once the circlular buffer is full.

Thanks for the package by the way. Even though I dont use it now I really appreciate it and might use it in the future.

**Comment by tbreloff** [comment] 2015-08-28 11:35
Fair enough, but that's a small implementation detail. We could support both.
